name: eng-pred
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - boto3
  - pyarrow
  - google-cloud-storage
  - polars
  - requests
  - sentence-transformers
  - pyyaml
  - pytest
  - conda-lock

  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1

  - pip
  - pip:
    - clearml
