name: eng-pred
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - boto3
  - pyarrow
  - google-cloud-storage
  - polars
  - requests
  - sentence-transformers
  - pyyaml

  - pytorch
  - torchvision
  - torchaudio
  # - pytorch-cuda=12.1

  - pip