name: vox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - boto3
  - pyarrow
  - pip
  - google-cloud-storage
  - pip:
    - torch
    - torchvision
    - sentence-transformers
    - requests
