name: eng-pred
channels:
  - pytorch
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11

  # core
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - pyyaml
  - python-dotenv
  - pytest
  - requests

  # data / IO
  - pyarrow<21
  - polars
  - boto3
  - google-cloud-storage

  # HF / embeddings
  - sentence-transformers

  # pytorch + cuda (conda)
  - pytorch
  - torchvision
  - torchaudio

  # tooling
  - conda-lock

  # pip-only deps
  - pip
  - pip:
      - clearml
